### ISSUE TITLE
Hupper fails in some topics

### ISSUE THREAD

**Issue by manfreed** [Ajnasz/hupper#24]
This topic triggers the error:
http://hup.hu/node/152356

Hupper runs partially, comments are not transformet, no next,prev links, "új" is not replaced, etc.

Chrome (56.0.2924.87),  Hupper (2.1.6)

Trace from console:

    Error in event handler for (unknown): TypeError: Cannot read property 'querySelector' of null
        at addFooterLink (chrome-extension://gpgbdmgjfdfjkfgogmfokkmfoacbdghj/data/bundle.js:1265:33)
        at addParentLinkToComment (chrome-extension://gpgbdmgjfdfjkfgogmfokkmfoacbdghj/data/bundle.js:1293:3)
        at Object.addParentLinkToComments (chrome-extension://gpgbdmgjfdfjkfgogmfokkmfoacbdghj/data/bundle.js:1307:12)
        at chrome-extension://gpgbdmgjfdfjkfgogmfokkmfoacbdghj/data/bundle.js:1984:16

**Comment by szenti** [comment]
It's fixed in 2.1.7. See: https://github.com/Ajnasz/hupper/issues/23

**Comment by Ajnasz** [comment]
Well, it's fixed in terms that the JS error will not be thrown, but because one comment screws up the markup of the page, all the other comments after that "bad" comment will not be parsed correctly.

**Comment by Ajnasz** [comment]
Thanks anyway for the bug report and for the help!

**Comment by manfreed** [comment]
No problem :) I might have a fix though. 

If I understand correctly the issue is that bad markup causes the footer to be placed outside the comment's div where the code expects it to be.

That's not hard to fix we just have to look for it if it's not where it should be.

Here is a simple code I was toying with just before, it helps in this exact case. I can only hope that similar situations has the same side effect (footer appearing next to the comment block). 

It's to late to do a proper pull request, but here is my fix:

    if (!commentObj.footer && node.nextElementSibling.classList.contains(COMMENT_FOOTER_CLASS)) {
        commentObj.footer = node.nextElementSibling;
        if (commentObj.footer) {
            node.appendChild(commentObj.footer);
        }
    }

I even place the footer back where it belongs. No proper testing done, but it works for me using my local build and looking at the topic I mentioned. 

I hope it helps and it's not too hacky.

**Comment by Ajnasz** [comment]
I released a 2.1.9 version today, where I improved the way how the comments are collected and parsed. see #25

**Comment by szenti** [comment]
@Ajnasz thank you.
