### ISSUE TITLE
Hupper doesn't find all the new comments

### ISSUE THREAD

**Issue by szenti** [Ajnasz/hupper#25]
Dear Ajnasz,

I was reading a long topic (https://hup.hu/node/152356?comments_per_page=9999#) when I realized that Hupper can't find all the new comments. First comment: http://imgur.com/09ebjvf, which Hupper identifies as the 'last' one. However a newer comment still exists: http://imgur.com/JLpshw9. Can you please have a look at it? (There are no JS errors in the console.)

**Comment by Ajnasz** [comment]
Released in 2.1.9
