### ISSUE TITLE
Doesn't work on Firefox 52

### ISSUE THREAD

**Issue by spymorass** [Ajnasz/hupper#26]
After upgrading Firefox to version 52, the extension stopped working. Reinstalling the extension didn't solve the problem.

**Comment by Ajnasz** [comment]
Should be fixed in 2.1.8.
I uploaded the new version to addons.mozilla.org, it will be available after the review process (it takes some time :( )
I will close the issue after the review.

**Comment by enpassant** [comment]
It works! :-) Thank you very much!
