### ISSUE TITLE
twitter filter pls!

### ISSUE THREAD

**Issue by qji77** [Ajnasz/hupper#34]
There are more and more twitter content on the main page what makes it hard to read. I think it would be enough to filter out the pictures from twitter, but I am happy with any other solution which gives back the old HUP style when we had more text then images.
Thanks!

**Comment by Ajnasz** [comment]
Hey!

Published to [development channel](https://addons.mozilla.org/en-US/firefox/addon/hupper/).
If you wan't to try on Chrome, please [contact me](https://ajnasz.hu/contact), I will need a google account enabled email address, so you can access to it.

**Comment by Ajnasz** [comment]
Released in v2.5.0
