### ISSUE TITLE
Grammatical errors in automatic HTML formatter function

### ISSUE THREAD

**Issue by bozsikarmand** [Ajnasz/hupper#35]
Hello,

Today as I wanted to send a message which contained HTML formatted elements, I received the following message:

"HTML formázási hibát találtam

Valószínűleg egy vagy több HTML taget nincs lezárva ahozzászólásban. Ez sok esetben az oldal helytelen megjelenéséhez vezethet.Kérlek ellenőrizd, hogy minden formázást jól alkalmaztál-e, esetlegpróbáld ki az automatikus javítást!"

And the two buttons underneath:

"Automatikus javítás" and "Nem, baj, tovább"

These are situated in "hupper-error-message-container" div.

As you can see, there are grammatical errors in the original text. Something like this would be better in my opinion:

"HTML formázási hibát találtam!

Valószínűleg egy vagy több HTML taget nem zártál le hozzászólásodban. Ez sok esetben az oldal helytelen megjelenéséhez vezethet. Kérlek ellenőrizd, hogy minden formázást jól alkalmaztál-e, esetleg próbáld ki az automatikus javítást!"

And the two buttons underneath should look like, just for clarification:

"Automatikus javítás" and "Mellőzöm az automatikus javítást, továbblépek"

Thanks!

**Comment by Ajnasz** [comment]
That's great, thanks!

> Mellőzöm az automatikus javítást, továbblépek

Do you have an idea how to make it a bit shorter, like 20-30 chars?

**Comment by bozsikarmand** [comment]
Sure!
As an alternative, I can offer the one above and maybe it would fit your needs better as well. :) 

> Továbblépek, javitás nélkül

Which is 27 characters in length.
