### ISSUE TITLE
Komment előnézet átugrása

### ISSUE THREAD

**Issue by SPYFF** [Ajnasz/hupper#42]
Egy ideje komment beküldése előtt kötelezően előnézet van aztán lehet csak beküldeni. Jó lenne egy azonnali beküldés gomb a pluginnal.

**Comment by Ajnasz** [comment]
Az lehet, hogy már nem is kell ez a funkció? Mintha folyton ott lenne a Beküldés gomb a hozzászólásoknál.

**Comment by SPYFF** [comment]
Igen, most már én is látom (simán lehet, hogy trey olvasta itt a kommenteket és visszarakta).
